### ISSUE TITLE
Erst erstelltes Fach wird nicht angezeigt.

### ISSUE THREAD

**Issue by Mortgu** [IamPekka058/schooly#1]
Nachdem das Profil erstellt wurde und Mann sein erstes Fach hinzufügen möchte, muss die App neu gestartet werden.

**Comment by IamPekka058** [comment]
Besteht das Problem im Alpha-Test Patch 4 (1.0.2) Release?

**Comment by IamPekka058** [comment]
Der Bug wurde mit dem Alpha-Patch 4 (1.0.2) behoben.
